name: Atualizar Dados do Instagram

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 3AM (horário UTC)
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install instaloader flask pandas

    - name: Executar coleta
      run: |
        python update_data.py
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/rankings.json
        git commit -m "Atualiza ranking automático"
        git push
